<?php
namespace App\Enum;


enum DeliveryOrderStatus:string
{
    case MENUNGGU_KONFIRMASI_ADMIN_GUDANG = 'MENUNGGU_KONFIRMASI_ADMIN_GUDANG';
    case MENUNGGU_KONFIRMASI_DRIVER = 'MENUNGGU_KONFIRMASI_DRIVER';
    case DRIVER_DALAM_PERJALANAN = 'DRIVER_DALAM_PERJALANAN';
    case SELESAI = 'SELESAI';
}