<?php
namespace App\Enum;


enum PenggunaanStatus:string
{
    case MENUNGGU_SURAT_JALAN = 'MENUNGGU_SURAT_JALAN';
    case MENUNGGU_PENGIRIMAN = 'MENUNGGU_PENGIRIMAN';
    case MENUNGGU_PENGEMBALIAN = 'MENUNGGU_PENGEMBALIAN';
    case SEDANG_DIKIRIM = 'SEDANG_DIKIRIM';
    case DIGUNAKAN = 'DIGUNAKAN';
    case SELESAI = 'SELESAI';
}